# -*- coding: utf-8 -*-
"""SLR0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-b5UdSHREqlzRaeegZ-U4iiZkEVvsOB

# **House Price Prediction**
"""

# Commented out IPython magic to ensure Python compatibility.
# step 1: Install required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# step 2 : Load the dataset

USAhousingData = pd.read_csv("/content/USA_Housing.csv")

# print("USAhousingData : " , USAhousingData)

# Data Preprocessing

USAhousingData.head()

USAhousingData.info()

USAhousingData.describe()

# Feature Engineering

USAhousingData = USAhousingData.drop('Address',axis=1)

sns.heatmap(USAhousingData.corr())

plt.scatter(USAhousingData['Avg. Area Income'],USAhousingData['Price'])

plt.scatter(USAhousingData['Avg. Area House Age'],USAhousingData['Price'])

plt.scatter(USAhousingData['Area Population'],USAhousingData['Price'])

sns.pairplot(USAhousingData)

sns.displot(USAhousingData['Price'])

# Model Training

# step 1:getting values of independent and dependent variables

x = USAhousingData.drop('Price',axis=1)
y=USAhousingData["Price"]

x

y

# step 2 : splitting the dataset
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.4,random_state=101)

# step 3 : import and train the model
from sklearn.linear_model import LinearRegression

lm = LinearRegression()

lm.fit(x_train,y_train)

# Model Prediction

predictions = lm.predict(x_test)

plt.scatter(y_test,predictions)

# Model Evaluation

from sklearn import metrics

print("MAE : " , metrics.mean_absolute_error(y_test,predictions))

print("MSE : " , metrics.mean_squared_error(y_test,predictions))

print("RMSE : " , np.sqrt(metrics.mean_squared_error(y_test,predictions)))

